version: "3.8"
services:
  frontend:
    build:
      context: ./bob
    network_mode: host
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=/api
    command: npm start

  backend:
    build:
      context: ./server
    network_mode: host
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run start:prod

  nginx:
    build:
      context: ./nginx
    network_mode: host
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    environment:
      - DOMAIN=${DOMAIN}
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        envsubst '$${DOMAIN}' < /etc/nginx/conf.d/myapp.conf.template > /etc/nginx/conf.d/myapp.conf
        nginx -g 'daemon off;'
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    network_mode: host
    profiles: ["new"]
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: >
      certonly --standalone
      --email ${EMAIL}
      --agree-tos --no-eff-email 
      -d ${DOMAIN} -d www.${DOMAIN}

  certbot-renew:
    image: certbot/certbot
    network_mode: host
    profiles: ["renewal"]
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      renew --standalone
