version: "3.8"
services:
  frontend:
    build:
      context: ./bob
    network_mode: host
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=/api
    command: npm start
    restart: unless-stopped

  backend:
    build:
      context: ./server
    network_mode: host
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start:prod
    restart: unless-stopped
